version: '3.9'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    platform: linux/amd64
    image: mysql:5.7.40
    container_name: mysql
    #    command: --ddefault-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./docker/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: "12345"